"""Ajout champ description dans rating

Revision ID: 0b8e131f9953
Revises: d58896ec25c6
Create Date: 2022-03-28 14:28:53.789414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8e131f9953'
down_revision = 'd58896ec25c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'description')
    # ### end Alembic commands ###
